name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GIT_SUBMODULE_STRATEGY: recursive

permissions:
  contents: write

jobs:
  build-desktop:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-latest ]

    steps:
      - name: Fetch sources
        uses: actions/checkout@v5.0.0

      # Cache AUI boot directory
      - name: Cache AUI.BOOT deps
        id: cache-aui-boot
        uses: actions/cache@v4.2.4
        env:
          cache-name: aui-boot
        with:
          path: ~/.aui
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y pkg-config libglew-dev zlib1g-dev libssl-dev libcrypt-dev libcurl4-openssl-dev libgtk-3-dev libfontconfig-dev ninja-build libpulse-dev

      - name: Set up CMake (Windows)
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@v3.24.3

      - name: Load Visual C++ ${{matrix.arch.vsversion}} Toolkit and Platform SDK 2010
        if: runner.os == 'Windows'
        uses: "./.github/actions/load-vs2010"
        with:
          nocache: ${{vars.NOCACHE}}

      - name: Configure CMake
        run: cmake -G "${{ matrix.os=='windows-2022' && 'Visual Studio 10 2010' || 'Ninja' }}" -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{ matrix.additional_cmake_flags }} -DAUI_INSTALL_RUNTIME_DEPENDENCIES=TRUE -D_WIN32_WINNT=0x502

      - name: Build Project
        run: cmake --build ${{ github.workspace }}/build --config RelWithDebInfo

      - name: Build Tests
        run: cmake --build ${{ github.workspace }}/build --config RelWithDebInfo --target Tests

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}/build
        run: ctest -C RelWithDebInfo --output-on-failure

      - name: Run Tests (Linux)
        if: runner.os == 'Linux'
        working-directory: ${{ github.workspace }}/build/bin
        run: ${{ github.workspace }}/build/bin/Tests

      - name: Pack Windows Setup
        if: runner.os == 'Windows'
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake . -DAUI_APP_PACKAGING=INNOSETUP
          cmake --build . --config RelWithDebInfo
          cpack . -CRelWithDebInfo -B artifacts

      - name: Pack Windows Portable
        if: runner.os == 'Windows'
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake . -DAUI_APP_PACKAGING=AUI_PORTABLE_ZIP
          cmake --build . --config RelWithDebInfo
          cpack . -CRelWithDebInfo -B artifacts

      - name: Pack Linux Portable (ZIP)
        if: runner.os == 'Linux'
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake . -DAUI_APP_PACKAGING=AUI_PORTABLE_ZIP
          cmake --build . --config RelWithDebInfo
          cpack . -CRelWithDebInfo -B artifacts

      - name: Pack Linux Portable (tar.gz)
        if: runner.os == 'Linux'
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake . -DAUI_APP_PACKAGING=AUI_PORTABLE_TGZ
          cmake --build . --config RelWithDebInfo
          cpack . -CRelWithDebInfo -B artifacts

      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ${{ github.workspace }}/build/artifacts/*.*
          name: desktop-${{ runner.os }}-r${{ github.run_attempt }}
          if-no-files-found: error

  release-draft:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name != 'pull_request'
    needs: [ build-desktop ]
    name: Release draft
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5.0.0

      - name: Extract version
        run: |
          VERSION=$(grep -Po '[0-9\.]+(?= # CI_PROJECT_VERSION)' CMakeLists.txt)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSION = $VERSION"

      # Remove old release drafts
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -r -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      # Download all desktop artifacts
      - name: Download desktop artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/desktop
          pattern: desktop-*

      # Flatten all artifact files into a single folder
      - name: Merge artifacts
        run: |
          mkdir -p artifacts/all
          # copy only actual files from both sets
          find artifacts/desktop -type f -exec cp {} artifacts/all/ \;
          echo "Final files to upload:"
          ls -al artifacts/all

      # Create a new draft release with all artifacts
      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --draft \
            --title "v${{ env.VERSION }}" \
            --target "$GITHUB_SHA" \
            artifacts/all/*
